#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

void matrix_add(int * srt, int size, int scalar);
//main
int main(int argc, char * argv[]){
	FILE * fr = fopen("matrix.txt","r");
	
	if(fr == NULL){
		fprintf(stderr, "File failed to open\n");
	}

	// i will be using this to read from the file.
	int index = 0, scalar = 0, k;

	// om = original matrix; matrix generated by matrix_gen
	int  om;

	// new matrix or the new buffer
	int  nm[16];

	srand(time(NULL));

	// read the file while performing the scalar addition and saving to a new buffer.
	fscanf(fr, "%d", &k);
	while(!feof(fr)){
		
		//printf("%d\n", om);
		
		// generate the new random int for scalar;
		scalar  = rand() % 100;

		// adding the block aand scalar at index.
		nm[index] = k + scalar;

		// also for testing.
		//printf("new number for: %d + Scalar: %d = %d\n", k, scalar, nm[index]);

		// reading a new int from file
		fscanf(fr, "%d", &k);
		
		// i dont want to determine the size.
		index++;

		fflush(stdout);
	}
	//\let's print this to a file .
	matrix_add(nm, index, scalar);

	// testing
	printf("Counter = %d\n", index);

	/* End of testing*/

}//end of main

// helper class matrix add which will add the new block to a file 
void matrix_add(int * srt, int size, int scalar){
	FILE * newMatrix = fopen("NewMatrix.txt", "w");

	int mn[size][size];

	int count=0,count2=0; 


	for(int i = 0; i < size; i++){
		for(int j=0; j < size; j++){

			//mn[i][j] = 


			if(count == size){
				fprintf(newMatrix,"\n");
				count=0;
			}

			fprintf(newMatrix," %d ",mn[i][j]);
		

			if(count2 == size*size -1){
				
				fprintf(newMatrix,"\n");
			}
			count++;

			count2++;

		}//end of j loop
	}// enf of i loop



}// end of matrix_add